name: app_crypto
description: Example Flutter Application with Bloc & Freezed + Dio & Retrofit for API REST. Specifically for Antoine challenge :)

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  google_fonts: ^3.0.1
  flutter_hooks: ^0.18.5+1
  fl_chart: ^0.55.1
  modal_bottom_sheet: ^2.1.0
  build_runner: ^2.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  hydrated_bloc: ^9.0.0-dev.3
  crypto_currency_repository:
    path: packages/crypto_currency_repository
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  bloc_concurrency: ^0.2.0
  intl: ^0.17.0
  easy_localization: ^3.0.1
  adaptive_dialog: ^1.8.0
  tuple: ^2.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/