// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'coin_detailed.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_CoinDetailed _$$_CoinDetailedFromJson(Map<String, dynamic> json) =>
    _$_CoinDetailed(
      id: json['id'] as String?,
      symbol: json['symbol'] as String?,
      name: json['name'] as String?,
      assetPlatformId: json['assetPlatformId'] as String?,
      platforms: (json['platforms'] as List<dynamic>)
          .map((e) => e as String?)
          .toList(),
      blockTimeInMinutes: json['blockTimeInMinutes'] as int?,
      hashingAlgorithm: json['hashingAlgorithm'] as String?,
      categories: (json['categories'] as List<dynamic>)
          .map((e) => e as String?)
          .toList(),
      publicNotice: json['publicNotice'] as String?,
      additionalNotices: (json['additionalNotices'] as List<dynamic>)
          .map((e) => e as String?)
          .toList(),
      localization: json['localization'] == null
          ? null
          : Localization.fromJson(json['localization'] as Map<String, dynamic>),
      description: json['description'] == null
          ? null
          : Description.fromJson(json['description'] as Map<String, dynamic>),
      image: json['image'] == null
          ? null
          : Image.fromJson(json['image'] as Map<String, dynamic>),
      countryOrigin: json['countryOrigin'] as String?,
      genesisDate: json['genesisDate'] == null
          ? null
          : DateTime.parse(json['genesisDate'] as String),
      sentimentVotesUpPercentage:
          (json['sentimentVotesUpPercentage'] as num?)?.toDouble(),
      sentimentVotesDownPercentage:
          (json['sentimentVotesDownPercentage'] as num?)?.toDouble(),
      marketCapRank: json['marketCapRank'] as int?,
      coingeckoRank: json['coingeckoRank'] as int?,
      coingeckoScore: (json['coingeckoScore'] as num?)?.toDouble(),
      developerScore: (json['developerScore'] as num?)?.toDouble(),
      communityScore: (json['communityScore'] as num?)?.toDouble(),
      liquidityScore: (json['liquidityScore'] as num?)?.toDouble(),
      publicInterestScore: (json['publicInterestScore'] as num?)?.toDouble(),
      marketData: json['marketData'] == null
          ? null
          : MarketData.fromJson(json['marketData'] as Map<String, dynamic>),
      lastUpdated: json['lastUpdated'] == null
          ? null
          : DateTime.parse(json['lastUpdated'] as String),
    );

Map<String, dynamic> _$$_CoinDetailedToJson(_$_CoinDetailed instance) =>
    <String, dynamic>{
      'id': instance.id,
      'symbol': instance.symbol,
      'name': instance.name,
      'assetPlatformId': instance.assetPlatformId,
      'platforms': instance.platforms,
      'blockTimeInMinutes': instance.blockTimeInMinutes,
      'hashingAlgorithm': instance.hashingAlgorithm,
      'categories': instance.categories,
      'publicNotice': instance.publicNotice,
      'additionalNotices': instance.additionalNotices,
      'localization': instance.localization,
      'description': instance.description,
      'image': instance.image,
      'countryOrigin': instance.countryOrigin,
      'genesisDate': instance.genesisDate?.toIso8601String(),
      'sentimentVotesUpPercentage': instance.sentimentVotesUpPercentage,
      'sentimentVotesDownPercentage': instance.sentimentVotesDownPercentage,
      'marketCapRank': instance.marketCapRank,
      'coingeckoRank': instance.coingeckoRank,
      'coingeckoScore': instance.coingeckoScore,
      'developerScore': instance.developerScore,
      'communityScore': instance.communityScore,
      'liquidityScore': instance.liquidityScore,
      'publicInterestScore': instance.publicInterestScore,
      'marketData': instance.marketData,
      'lastUpdated': instance.lastUpdated?.toIso8601String(),
    };

_$_Image _$$_ImageFromJson(Map<String, dynamic> json) => _$_Image(
      thumb: json['thumb'] as String?,
      small: json['small'] as String?,
      large: json['large'] as String?,
    );

Map<String, dynamic> _$$_ImageToJson(_$_Image instance) => <String, dynamic>{
      'thumb': instance.thumb,
      'small': instance.small,
      'large': instance.large,
    };

_$_MarketData _$$_MarketDataFromJson(Map<String, dynamic> json) =>
    _$_MarketData(
      currentPrice:
          CurrentPrice.fromJson(json['currentPrice'] as Map<String, dynamic>),
      roi: json['roi'] as String?,
      marketCap: MarketCap.fromJson(json['marketCap'] as Map<String, dynamic>),
      marketCapRank: json['marketCapRank'] as int,
      totalVolume:
          TotalVolume.fromJson(json['totalVolume'] as Map<String, dynamic>),
      high24h: High24h.fromJson(json['high24h'] as Map<String, dynamic>),
      low24h: Low24h.fromJson(json['low24h'] as Map<String, dynamic>),
      priceChange24h: (json['priceChange24h'] as num).toDouble(),
      priceChangePercentage24h:
          (json['priceChangePercentage24h'] as num).toDouble(),
      priceChangePercentage7d:
          (json['priceChangePercentage7d'] as num).toDouble(),
      priceChangePercentage14d:
          (json['priceChangePercentage14d'] as num).toDouble(),
      priceChangePercentage30d:
          (json['priceChangePercentage30d'] as num).toDouble(),
      priceChangePercentage60d:
          (json['priceChangePercentage60d'] as num).toDouble(),
      priceChangePercentage200d:
          (json['priceChangePercentage200d'] as num).toDouble(),
      priceChangePercentage1y:
          (json['priceChangePercentage1y'] as num).toDouble(),
      marketCapChange24h: (json['marketCapChange24h'] as num).toDouble(),
      marketCapChangePercentage24h:
          (json['marketCapChangePercentage24h'] as num).toDouble(),
      priceChange24hInCurrency: PriceChange24hInCurrency.fromJson(
          json['priceChange24hInCurrency'] as Map<String, dynamic>),
      priceChangePercentage1hInCurrency:
          PriceChangePercentage1hInCurrency.fromJson(
              json['priceChangePercentage1hInCurrency']
                  as Map<String, dynamic>),
      priceChangePercentage24hInCurrency:
          PriceChangePercentage24hInCurrency.fromJson(
              json['priceChangePercentage24hInCurrency']
                  as Map<String, dynamic>),
      priceChangePercentage7dInCurrency:
          PriceChangePercentage7dInCurrency.fromJson(
              json['priceChangePercentage7dInCurrency']
                  as Map<String, dynamic>),
      priceChangePercentage14dInCurrency:
          PriceChangePercentage14dInCurrency.fromJson(
              json['priceChangePercentage14dInCurrency']
                  as Map<String, dynamic>),
      priceChangePercentage30dInCurrency:
          PriceChangePercentage30dInCurrency.fromJson(
              json['priceChangePercentage30dInCurrency']
                  as Map<String, dynamic>),
      priceChangePercentage60dInCurrency:
          PriceChangePercentage60dInCurrency.fromJson(
              json['priceChangePercentage60dInCurrency']
                  as Map<String, dynamic>),
      priceChangePercentage200dInCurrency:
          PriceChangePercentage200dInCurrency.fromJson(
              json['priceChangePercentage200dInCurrency']
                  as Map<String, dynamic>),
      priceChangePercentage1yInCurrency:
          PriceChangePercentage1yInCurrency.fromJson(
              json['priceChangePercentage1yInCurrency']
                  as Map<String, dynamic>),
      marketCapChange24hInCurrency: MarketCapChange24hInCurrency.fromJson(
          json['marketCapChange24hInCurrency'] as Map<String, dynamic>),
      marketCapChangePercentage24hInCurrency:
          MarketCapChangePercentage24hInCurrency.fromJson(
              json['marketCapChangePercentage24hInCurrency']
                  as Map<String, dynamic>),
      totalSupply: (json['totalSupply'] as num).toDouble(),
      circulatingSupply: (json['circulatingSupply'] as num).toDouble(),
    );

Map<String, dynamic> _$$_MarketDataToJson(_$_MarketData instance) =>
    <String, dynamic>{
      'currentPrice': instance.currentPrice,
      'roi': instance.roi,
      'marketCap': instance.marketCap,
      'marketCapRank': instance.marketCapRank,
      'totalVolume': instance.totalVolume,
      'high24h': instance.high24h,
      'low24h': instance.low24h,
      'priceChange24h': instance.priceChange24h,
      'priceChangePercentage24h': instance.priceChangePercentage24h,
      'priceChangePercentage7d': instance.priceChangePercentage7d,
      'priceChangePercentage14d': instance.priceChangePercentage14d,
      'priceChangePercentage30d': instance.priceChangePercentage30d,
      'priceChangePercentage60d': instance.priceChangePercentage60d,
      'priceChangePercentage200d': instance.priceChangePercentage200d,
      'priceChangePercentage1y': instance.priceChangePercentage1y,
      'marketCapChange24h': instance.marketCapChange24h,
      'marketCapChangePercentage24h': instance.marketCapChangePercentage24h,
      'priceChange24hInCurrency': instance.priceChange24hInCurrency,
      'priceChangePercentage1hInCurrency':
          instance.priceChangePercentage1hInCurrency,
      'priceChangePercentage24hInCurrency':
          instance.priceChangePercentage24hInCurrency,
      'priceChangePercentage7dInCurrency':
          instance.priceChangePercentage7dInCurrency,
      'priceChangePercentage14dInCurrency':
          instance.priceChangePercentage14dInCurrency,
      'priceChangePercentage30dInCurrency':
          instance.priceChangePercentage30dInCurrency,
      'priceChangePercentage60dInCurrency':
          instance.priceChangePercentage60dInCurrency,
      'priceChangePercentage200dInCurrency':
          instance.priceChangePercentage200dInCurrency,
      'priceChangePercentage1yInCurrency':
          instance.priceChangePercentage1yInCurrency,
      'marketCapChange24hInCurrency': instance.marketCapChange24hInCurrency,
      'marketCapChangePercentage24hInCurrency':
          instance.marketCapChangePercentage24hInCurrency,
      'totalSupply': instance.totalSupply,
      'circulatingSupply': instance.circulatingSupply,
    };

_$_CurrentPrice _$$_CurrentPriceFromJson(Map<String, dynamic> json) =>
    _$_CurrentPrice(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      trY: (json['trY'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      ats: (json['ats'] as num).toDouble(),
    );

Map<String, dynamic> _$$_CurrentPriceToJson(_$_CurrentPrice instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_MarketCap _$$_MarketCapFromJson(Map<String, dynamic> json) => _$_MarketCap(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      trY: (json['trY'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      ats: (json['ats'] as num).toDouble(),
    );

Map<String, dynamic> _$$_MarketCapToJson(_$_MarketCap instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_TotalVolume _$$_TotalVolumeFromJson(Map<String, dynamic> json) =>
    _$_TotalVolume(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      trY: (json['trY'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      ats: (json['ats'] as num).toDouble(),
    );

Map<String, dynamic> _$$_TotalVolumeToJson(_$_TotalVolume instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_High24h _$$_High24hFromJson(Map<String, dynamic> json) => _$_High24h(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      trY: (json['trY'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      ats: (json['ats'] as num).toDouble(),
    );

Map<String, dynamic> _$$_High24hToJson(_$_High24h instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_Low24h _$$_Low24hFromJson(Map<String, dynamic> json) => _$_Low24h(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      trY: (json['trY'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      ats: (json['ats'] as num).toDouble(),
    );

Map<String, dynamic> _$$_Low24hToJson(_$_Low24h instance) => <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChange24hInCurrency _$$_PriceChange24hInCurrencyFromJson(
        Map<String, dynamic> json) =>
    _$_PriceChange24hInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      trY: (json['trY'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      ats: (json['ats'] as num).toDouble(),
    );

Map<String, dynamic> _$$_PriceChange24hInCurrencyToJson(
        _$_PriceChange24hInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChangePercentage24hInCurrency
    _$$_PriceChangePercentage24hInCurrencyFromJson(Map<String, dynamic> json) =>
        _$_PriceChangePercentage24hInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_PriceChangePercentage24hInCurrencyToJson(
        _$_PriceChangePercentage24hInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChangePercentage1hInCurrency
    _$$_PriceChangePercentage1hInCurrencyFromJson(Map<String, dynamic> json) =>
        _$_PriceChangePercentage1hInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_PriceChangePercentage1hInCurrencyToJson(
        _$_PriceChangePercentage1hInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChangePercentage7dInCurrency
    _$$_PriceChangePercentage7dInCurrencyFromJson(Map<String, dynamic> json) =>
        _$_PriceChangePercentage7dInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_PriceChangePercentage7dInCurrencyToJson(
        _$_PriceChangePercentage7dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChangePercentage14dInCurrency
    _$$_PriceChangePercentage14dInCurrencyFromJson(Map<String, dynamic> json) =>
        _$_PriceChangePercentage14dInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_PriceChangePercentage14dInCurrencyToJson(
        _$_PriceChangePercentage14dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChangePercentage30dInCurrency
    _$$_PriceChangePercentage30dInCurrencyFromJson(Map<String, dynamic> json) =>
        _$_PriceChangePercentage30dInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_PriceChangePercentage30dInCurrencyToJson(
        _$_PriceChangePercentage30dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChangePercentage60dInCurrency
    _$$_PriceChangePercentage60dInCurrencyFromJson(Map<String, dynamic> json) =>
        _$_PriceChangePercentage60dInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_PriceChangePercentage60dInCurrencyToJson(
        _$_PriceChangePercentage60dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChangePercentage200dInCurrency
    _$$_PriceChangePercentage200dInCurrencyFromJson(
            Map<String, dynamic> json) =>
        _$_PriceChangePercentage200dInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_PriceChangePercentage200dInCurrencyToJson(
        _$_PriceChangePercentage200dInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_PriceChangePercentage1yInCurrency
    _$$_PriceChangePercentage1yInCurrencyFromJson(Map<String, dynamic> json) =>
        _$_PriceChangePercentage1yInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_PriceChangePercentage1yInCurrencyToJson(
        _$_PriceChangePercentage1yInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_MarketCapChange24hInCurrency _$$_MarketCapChange24hInCurrencyFromJson(
        Map<String, dynamic> json) =>
    _$_MarketCapChange24hInCurrency(
      aed: (json['aed'] as num).toDouble(),
      ars: (json['ars'] as num).toDouble(),
      aud: (json['aud'] as num).toDouble(),
      bch: (json['bch'] as num).toDouble(),
      bdt: (json['bdt'] as num).toDouble(),
      bhd: (json['bhd'] as num).toDouble(),
      bmd: (json['bmd'] as num).toDouble(),
      bnb: (json['bnb'] as num).toDouble(),
      brl: (json['brl'] as num).toDouble(),
      btc: (json['btc'] as num).toDouble(),
      cad: (json['cad'] as num).toDouble(),
      chf: (json['chf'] as num).toDouble(),
      clp: (json['clp'] as num).toDouble(),
      cny: (json['cny'] as num).toDouble(),
      czk: (json['czk'] as num).toDouble(),
      dkk: (json['dkk'] as num).toDouble(),
      dot: (json['dot'] as num).toDouble(),
      eos: (json['eos'] as num).toDouble(),
      eth: (json['eth'] as num).toDouble(),
      eur: (json['eur'] as num).toDouble(),
      gbp: (json['gbp'] as num).toDouble(),
      hkd: (json['hkd'] as num).toDouble(),
      huf: (json['huf'] as num).toDouble(),
      idr: (json['idr'] as num).toDouble(),
      ils: (json['ils'] as num).toDouble(),
      inr: (json['inr'] as num).toDouble(),
      jpy: (json['jpy'] as num).toDouble(),
      krw: (json['krw'] as num).toDouble(),
      kwd: (json['kwd'] as num).toDouble(),
      lkr: (json['lkr'] as num).toDouble(),
      ltc: (json['ltc'] as num).toDouble(),
      mmk: (json['mmk'] as num).toDouble(),
      mxn: (json['mxn'] as num).toDouble(),
      myr: (json['myr'] as num).toDouble(),
      ngn: (json['ngn'] as num).toDouble(),
      nok: (json['nok'] as num).toDouble(),
      nzd: (json['nzd'] as num).toDouble(),
      php: (json['php'] as num).toDouble(),
      pkr: (json['pkr'] as num).toDouble(),
      pln: (json['pln'] as num).toDouble(),
      rub: (json['rub'] as num).toDouble(),
      sar: (json['sar'] as num).toDouble(),
      sek: (json['sek'] as num).toDouble(),
      sgd: (json['sgd'] as num).toDouble(),
      thb: (json['thb'] as num).toDouble(),
      trY: (json['trY'] as num).toDouble(),
      twd: (json['twd'] as num).toDouble(),
      uah: (json['uah'] as num).toDouble(),
      usd: (json['usd'] as num).toDouble(),
      vef: (json['vef'] as num).toDouble(),
      vnd: (json['vnd'] as num).toDouble(),
      xag: (json['xag'] as num).toDouble(),
      xau: (json['xau'] as num).toDouble(),
      xdr: (json['xdr'] as num).toDouble(),
      xlm: (json['xlm'] as num).toDouble(),
      xrp: (json['xrp'] as num).toDouble(),
      yfi: (json['yfi'] as num).toDouble(),
      zar: (json['zar'] as num).toDouble(),
      bits: (json['bits'] as num).toDouble(),
      link: (json['link'] as num).toDouble(),
      ats: (json['ats'] as num).toDouble(),
    );

Map<String, dynamic> _$$_MarketCapChange24hInCurrencyToJson(
        _$_MarketCapChange24hInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_MarketCapChangePercentage24hInCurrency
    _$$_MarketCapChangePercentage24hInCurrencyFromJson(
            Map<String, dynamic> json) =>
        _$_MarketCapChangePercentage24hInCurrency(
          aed: (json['aed'] as num).toDouble(),
          ars: (json['ars'] as num).toDouble(),
          aud: (json['aud'] as num).toDouble(),
          bch: (json['bch'] as num).toDouble(),
          bdt: (json['bdt'] as num).toDouble(),
          bhd: (json['bhd'] as num).toDouble(),
          bmd: (json['bmd'] as num).toDouble(),
          bnb: (json['bnb'] as num).toDouble(),
          brl: (json['brl'] as num).toDouble(),
          btc: (json['btc'] as num).toDouble(),
          cad: (json['cad'] as num).toDouble(),
          chf: (json['chf'] as num).toDouble(),
          clp: (json['clp'] as num).toDouble(),
          cny: (json['cny'] as num).toDouble(),
          czk: (json['czk'] as num).toDouble(),
          dkk: (json['dkk'] as num).toDouble(),
          dot: (json['dot'] as num).toDouble(),
          eos: (json['eos'] as num).toDouble(),
          eth: (json['eth'] as num).toDouble(),
          eur: (json['eur'] as num).toDouble(),
          gbp: (json['gbp'] as num).toDouble(),
          hkd: (json['hkd'] as num).toDouble(),
          huf: (json['huf'] as num).toDouble(),
          idr: (json['idr'] as num).toDouble(),
          ils: (json['ils'] as num).toDouble(),
          inr: (json['inr'] as num).toDouble(),
          jpy: (json['jpy'] as num).toDouble(),
          krw: (json['krw'] as num).toDouble(),
          kwd: (json['kwd'] as num).toDouble(),
          lkr: (json['lkr'] as num).toDouble(),
          ltc: (json['ltc'] as num).toDouble(),
          mmk: (json['mmk'] as num).toDouble(),
          mxn: (json['mxn'] as num).toDouble(),
          myr: (json['myr'] as num).toDouble(),
          ngn: (json['ngn'] as num).toDouble(),
          nok: (json['nok'] as num).toDouble(),
          nzd: (json['nzd'] as num).toDouble(),
          php: (json['php'] as num).toDouble(),
          pkr: (json['pkr'] as num).toDouble(),
          pln: (json['pln'] as num).toDouble(),
          rub: (json['rub'] as num).toDouble(),
          sar: (json['sar'] as num).toDouble(),
          sek: (json['sek'] as num).toDouble(),
          sgd: (json['sgd'] as num).toDouble(),
          thb: (json['thb'] as num).toDouble(),
          trY: (json['trY'] as num).toDouble(),
          twd: (json['twd'] as num).toDouble(),
          uah: (json['uah'] as num).toDouble(),
          usd: (json['usd'] as num).toDouble(),
          vef: (json['vef'] as num).toDouble(),
          vnd: (json['vnd'] as num).toDouble(),
          xag: (json['xag'] as num).toDouble(),
          xau: (json['xau'] as num).toDouble(),
          xdr: (json['xdr'] as num).toDouble(),
          xlm: (json['xlm'] as num).toDouble(),
          xrp: (json['xrp'] as num).toDouble(),
          yfi: (json['yfi'] as num).toDouble(),
          zar: (json['zar'] as num).toDouble(),
          bits: (json['bits'] as num).toDouble(),
          link: (json['link'] as num).toDouble(),
          ats: (json['ats'] as num).toDouble(),
        );

Map<String, dynamic> _$$_MarketCapChangePercentage24hInCurrencyToJson(
        _$_MarketCapChangePercentage24hInCurrency instance) =>
    <String, dynamic>{
      'aed': instance.aed,
      'ars': instance.ars,
      'aud': instance.aud,
      'bch': instance.bch,
      'bdt': instance.bdt,
      'bhd': instance.bhd,
      'bmd': instance.bmd,
      'bnb': instance.bnb,
      'brl': instance.brl,
      'btc': instance.btc,
      'cad': instance.cad,
      'chf': instance.chf,
      'clp': instance.clp,
      'cny': instance.cny,
      'czk': instance.czk,
      'dkk': instance.dkk,
      'dot': instance.dot,
      'eos': instance.eos,
      'eth': instance.eth,
      'eur': instance.eur,
      'gbp': instance.gbp,
      'hkd': instance.hkd,
      'huf': instance.huf,
      'idr': instance.idr,
      'ils': instance.ils,
      'inr': instance.inr,
      'jpy': instance.jpy,
      'krw': instance.krw,
      'kwd': instance.kwd,
      'lkr': instance.lkr,
      'ltc': instance.ltc,
      'mmk': instance.mmk,
      'mxn': instance.mxn,
      'myr': instance.myr,
      'ngn': instance.ngn,
      'nok': instance.nok,
      'nzd': instance.nzd,
      'php': instance.php,
      'pkr': instance.pkr,
      'pln': instance.pln,
      'rub': instance.rub,
      'sar': instance.sar,
      'sek': instance.sek,
      'sgd': instance.sgd,
      'thb': instance.thb,
      'trY': instance.trY,
      'twd': instance.twd,
      'uah': instance.uah,
      'usd': instance.usd,
      'vef': instance.vef,
      'vnd': instance.vnd,
      'xag': instance.xag,
      'xau': instance.xau,
      'xdr': instance.xdr,
      'xlm': instance.xlm,
      'xrp': instance.xrp,
      'yfi': instance.yfi,
      'zar': instance.zar,
      'bits': instance.bits,
      'link': instance.link,
      'ats': instance.ats,
    };

_$_Localization _$$_LocalizationFromJson(Map<String, dynamic> json) =>
    _$_Localization(
      en: json['en'] as String?,
      de: json['de'] as String?,
      es: json['es'] as String?,
      fr: json['fr'] as String?,
      it: json['it'] as String?,
      pl: json['pl'] as String?,
      ro: json['ro'] as String?,
      hu: json['hu'] as String?,
      nl: json['nl'] as String?,
      pt: json['pt'] as String?,
      sv: json['sv'] as String?,
      vi: json['vi'] as String?,
      tr: json['tr'] as String?,
      ru: json['ru'] as String?,
      ja: json['ja'] as String?,
      zh: json['zh'] as String?,
      zhTw: json['zhTw'] as String?,
      ko: json['ko'] as String?,
      ar: json['ar'] as String?,
      th: json['th'] as String?,
      id: json['id'] as String?,
      cs: json['cs'] as String?,
      da: json['da'] as String?,
      el: json['el'] as String?,
      hi: json['hi'] as String?,
      no: json['no'] as String?,
      sk: json['sk'] as String?,
      uk: json['uk'] as String?,
      he: json['he'] as String?,
      fi: json['fi'] as String?,
      bg: json['bg'] as String?,
      hr: json['hr'] as String?,
      lt: json['lt'] as String?,
      sl: json['sl'] as String?,
    );

Map<String, dynamic> _$$_LocalizationToJson(_$_Localization instance) =>
    <String, dynamic>{
      'en': instance.en,
      'de': instance.de,
      'es': instance.es,
      'fr': instance.fr,
      'it': instance.it,
      'pl': instance.pl,
      'ro': instance.ro,
      'hu': instance.hu,
      'nl': instance.nl,
      'pt': instance.pt,
      'sv': instance.sv,
      'vi': instance.vi,
      'tr': instance.tr,
      'ru': instance.ru,
      'ja': instance.ja,
      'zh': instance.zh,
      'zhTw': instance.zhTw,
      'ko': instance.ko,
      'ar': instance.ar,
      'th': instance.th,
      'id': instance.id,
      'cs': instance.cs,
      'da': instance.da,
      'el': instance.el,
      'hi': instance.hi,
      'no': instance.no,
      'sk': instance.sk,
      'uk': instance.uk,
      'he': instance.he,
      'fi': instance.fi,
      'bg': instance.bg,
      'hr': instance.hr,
      'lt': instance.lt,
      'sl': instance.sl,
    };

_$_Description _$$_DescriptionFromJson(Map<String, dynamic> json) =>
    _$_Description(
      en: json['en'] as String?,
      de: json['de'] as String?,
      es: json['es'] as String?,
      fr: json['fr'] as String?,
      it: json['it'] as String?,
      pl: json['pl'] as String?,
      ro: json['ro'] as String?,
      hu: json['hu'] as String?,
      nl: json['nl'] as String?,
      pt: json['pt'] as String?,
      sv: json['sv'] as String?,
      vi: json['vi'] as String?,
      tr: json['tr'] as String?,
      ru: json['ru'] as String?,
      ja: json['ja'] as String?,
      zh: json['zh'] as String?,
      zhTw: json['zhTw'] as String?,
      ko: json['ko'] as String?,
      ar: json['ar'] as String?,
      th: json['th'] as String?,
      id: json['id'] as String?,
      cs: json['cs'] as String?,
      da: json['da'] as String?,
      el: json['el'] as String?,
      hi: json['hi'] as String?,
      no: json['no'] as String?,
      sk: json['sk'] as String?,
      uk: json['uk'] as String?,
      he: json['he'] as String?,
      fi: json['fi'] as String?,
      bg: json['bg'] as String?,
      hr: json['hr'] as String?,
      lt: json['lt'] as String?,
      sl: json['sl'] as String?,
    );

Map<String, dynamic> _$$_DescriptionToJson(_$_Description instance) =>
    <String, dynamic>{
      'en': instance.en,
      'de': instance.de,
      'es': instance.es,
      'fr': instance.fr,
      'it': instance.it,
      'pl': instance.pl,
      'ro': instance.ro,
      'hu': instance.hu,
      'nl': instance.nl,
      'pt': instance.pt,
      'sv': instance.sv,
      'vi': instance.vi,
      'tr': instance.tr,
      'ru': instance.ru,
      'ja': instance.ja,
      'zh': instance.zh,
      'zhTw': instance.zhTw,
      'ko': instance.ko,
      'ar': instance.ar,
      'th': instance.th,
      'id': instance.id,
      'cs': instance.cs,
      'da': instance.da,
      'el': instance.el,
      'hi': instance.hi,
      'no': instance.no,
      'sk': instance.sk,
      'uk': instance.uk,
      'he': instance.he,
      'fi': instance.fi,
      'bg': instance.bg,
      'hr': instance.hr,
      'lt': instance.lt,
      'sl': instance.sl,
    };
