import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'crypto_currency.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'crypto_currency.g.dart';

@freezed
class CryptoCurrency with _$CryptoCurrency {
  const factory CryptoCurrency({
    required String id,
    required String symbol,
    required String name,
  }) = _CryptoCurrency;

  factory CryptoCurrency.fromJson(Map<String, Object?> json)
  => _$CryptoCurrencyFromJson(json);

}